### ISSUE TITLE
Maintain binaries for ethereal

### ISSUE THREAD

**Issue by danimesq** [Floflis/meta#108]
Compile with Go for multiple targets, and provide them in our fork.

https://github.com/wealdtech/ethereal/issues/23
https://github.com/Floflis/ethereal/releases/tag/v2.3.25
http://golangcookbook.com/chapters/running/cross-compiling/

**Comment by DaniellMesquita** [comment]
Make an .sh installer for ethereal, and maybe also for ipget.

**Comment by danimesq** [comment]
ethereal now provides their own binaries.
