### ISSUE TITLE
Add QRL as a pre-installed application

### ISSUE THREAD

**Issue by jackalyst** [Floflis/meta#31]
The Quantum Resistant Ledger (QRL) project is designed to be fully post-quantum secure using PQ-CRYPTO recommended cryptography which fits the "Security" aspect of Floflis-linux.

Project Link: https://theqrl.org/
Webwallet: https://github.com/theQRL/qrl-wallet/

**Comment by DaniellMesquita** [comment]
Hi, @jackalyst
Thanks for your suggestion.
Appreciated if QRL creates a plugin for signing git commits, app packages and other things

**Comment by DaniellMesquita** [comment]
NSA may kill Floflis.
Or I may have the same destiny as Ian Murdock.
