### ISSUE TITLE
Have ZeroNet Preinstalled

### ISSUE THREAD

**Issue by styromaniac** [Floflis/meta#40]
‍Enable plugins:

- [x] PeerMessage
- [x] BackgroundProcessing
- [x] Torrent
- [ ] Gopher
- [ ] P

Other:

- [ ] Autorun
- [ ] Pre-installed sites
- [ ] Use IPv6 for UI: https://github.com/HelloZeroNet/ZeroNet/issues/2017

**Comment by DaniellMesquita** [comment]
ZeroNet is added, althrough it isn't with plugins enabled yet (PeerMessage, Torrent, Gopher, BackgroundProcessing)

**Comment by DaniellMesquita** [comment]
I'll edit your issue`s comment to add a tasklist

**Comment by DaniellMesquita** [comment]
- [ ] Use IPv6 for UI: https://github.com/HelloZeroNet/ZeroNet/issues/2017

**Comment by DaniellMesquita** [comment]
@styromaniac, what are the benefits of supporting ZeroNet, an place flooded of far-right activists and Bitcoin-maxis?

**Comment by styromaniac** [comment]
> @styromaniac, what are the benefits of supporting ZeroNet, an place flooded of far-right activists and Bitcoin-maxis?

Free speech.
Free speech.
Also, free speech.

**Comment by DaniellMesquita** [comment]
> Free speech.
> Free speech.
> Also, free speech.

It's weird how you claim to be trans but defines the far-right hate speech as "free speech".
April also presents as trans but says "lesbian trans women don't exist, if you support them you're transphobic".

So, now its confirmed what are like the users on ZeroNet. Far-right members who claim to be from some marginalized group while "fights" against that very group from inside out. Sorry, but I can't support this clownery.

**Comment by styromaniac** [comment]
> > Free speech.
> > Free speech.
> > Also, free speech.
> 
> It's weird how you claim to be trans but defines the far-right hate speech as "free speech".
> April also presents as trans but says "lesbian trans women don't exist, if you support them you're transphobic".
> 
> So, now its confirmed what are like the users on ZeroNet. Far-right members who claim to be from some marginalized group while "fights" against that very group from inside out. Sorry, but I can't support this clownery.

I didn't say that hate speech is free speech, you pedantic little prick.

**Comment by imachug** [comment]
@DaniellMesquita Please tell me about a better free-speech-supporting alternative.

**Comment by DaniellMesquita** [comment]
@styromaniac
> you pedantic little prick.

You took it too much to the personal side, even getting emotional about it and trying to offend me. Seems like this behavior an convention from ZeroNet users, as @imachug already did that before, as of other users on ZN itself.

> I didn't equate hate speech to free speech

Already did it.

@imachug 
> Please tell me about a better free-speech-supporting alternative.

Define "better".

**Comment by DaniellMesquita** [comment]
I have an concern about how decentralized networks could enable meetups from far-right mobs and other terrorists; centralized backdoors are already claiming to be here to take care of it, or decentralized bots could be an alternative to handle it.

I'm against far-right content being removed; the history should judge it; this kind of content should be hidden, instead.

**Comment by DaniellMesquita** [comment]
About free speech, I wouldn't act like the creator of Beaker Browser and ban people from an GitHub organization.

@styromaniac and @imachug are still welcome to have civilized discussions without acting like skepticals nor Bitcoin/ZeroNet maxis.

**Comment by styromaniac** [comment]
Sorry. I don't have unlimited time in the world to feed you attention for twisting my words. You'll be blocked. Have a nice life.

**Comment by DaniellMesquita** [comment]
@styromaniac
> Sorry. I don't have unlimited time in the world to feed you attention for twisting my words. You'll be blocked. Have a nice life.

Breaking your message facilitates reading it and also points which type of person you are: an narcisistical, which explains why you considered "far-right activists" as "Free speech. Free speech. Also, free speech."

> Sorry. I don't have unlimited time

Why limiting the absolute time and relativizing it? And why mettering people's time?

> in the world

Why appealing on your phrase and having fixation about "world"? I know I can't reach it, that the "world" is "right" and I'm wrong so I'm okay with it.

> feed you attention

What is the problem with eating/drinking?
And what is the problem of (positively) getting attention and care?
I strongly think you should seek for care.

> for twisting my words

So, you think reasoning is just about "words"?

> You'll be blocked

🤷‍♀️

> Have a nice life.

You also have an problem with "life"? Love yours, so you'll respect others'

**Comment by imachug** [comment]
I've made mistakes and I regret them. But there's a thing I surely did right, and it's getting into decentralized free speech networks.
