### ISSUE TITLE
Namecoin as pre-installed app

### ISSUE THREAD

**Issue by JeremyRand** [Floflis/meta#42]
Hello.  @DaniellMesquita (or someone impersonating him) requested over in the Namecoin Matrix channel that I file an issue here for adding Namecoin as a pre-installed app.  Thus, I am doing so.  Cheers!

**Comment by DaniellMesquita** [comment]
Hi @JeremyRand 
Yes, I've requested that on Riot.im

I'm in study about how implement it, and adding a tasklist of the implementation. Thanks for your suggestion

**Comment by DaniellMesquita** [comment]
- [ ] Install Open JRE/JDK
- [ ] Install Namecoin with two options: lightweight or downloading the blockchain

**Comment by DaniellMesquita** [comment]
@JeremyRand , what is the lightweight version?

**Comment by DaniellMesquita** [comment]
Namecoin's maintainer, @JeremyRand, have ignored.

Ethereum+ENS seems to be more than an good alternative, but the right direction.
Closing this issue.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/Floflis/meta/issues/40

**Comment by DaniellMesquita** [comment]
This issue has been moved into: https://github.com/Floflis/meta/issues/109
